apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
    prometheus.io/port: "8888"
  labels:
    app.kubernetes.io/component: kuberay-apiserver
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/component: {{ include "kuberay-apiserver.name" . }}
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    {{- toYaml .Values.service.ports | nindent 12 }}
